/*
 * MyDeficiency.java
 *
 */

package eye.acolite;


public class MyDeficiency extends javax.swing.JPanel {
    
    public MyDeficiency() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        angleLabel = new javax.swing.JLabel();
        majorLabel = new javax.swing.JLabel();
        majorField = new javax.swing.JTextField();
        angleField1 = new javax.swing.JTextField();
        minorLabel = new javax.swing.JLabel();
        minorField = new javax.swing.JTextField();
        TESLabel = new javax.swing.JLabel();
        TESField = new javax.swing.JTextField();
        SIndexLabel = new javax.swing.JLabel();
        SIndexField = new javax.swing.JTextField();
        CIndexLabel = new javax.swing.JLabel();
        CIndexField = new javax.swing.JTextField();

        angleLabel.setText("Angle");

        majorLabel.setText("Major");

        majorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majorFieldActionPerformed(evt);
            }
        });

        angleField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angleField1ActionPerformed(evt);
            }
        });

        minorLabel.setText("Minor");

        minorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minorFieldActionPerformed(evt);
            }
        });

        TESLabel.setText("TES");

        TESField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TESFieldActionPerformed(evt);
            }
        });

        SIndexLabel.setText("S-Index");

        SIndexField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIndexFieldActionPerformed(evt);
            }
        });

        CIndexLabel.setText("C-Index");

        CIndexField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIndexFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minorField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minorLabel)
                    .addComponent(angleField1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(majorField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(majorLabel)
                    .addComponent(angleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CIndexField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CIndexLabel)
                    .addComponent(TESField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SIndexField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SIndexLabel)
                    .addComponent(TESLabel))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TESLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TESField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SIndexLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SIndexField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CIndexLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CIndexField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(angleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(angleField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(majorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(majorField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(minorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minorField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void majorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_majorFieldActionPerformed

    private void angleField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angleField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angleField1ActionPerformed

    private void minorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minorFieldActionPerformed

    private void TESFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TESFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TESFieldActionPerformed

    private void SIndexFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIndexFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SIndexFieldActionPerformed

    private void CIndexFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIndexFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CIndexFieldActionPerformed
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CIndexField;
    private javax.swing.JLabel CIndexLabel;
    private javax.swing.JTextField SIndexField;
    private javax.swing.JLabel SIndexLabel;
    private javax.swing.JTextField TESField;
    private javax.swing.JLabel TESLabel;
    private javax.swing.JTextField angleField1;
    private javax.swing.JLabel angleLabel;
    private javax.swing.JTextField majorField;
    private javax.swing.JLabel majorLabel;
    private javax.swing.JTextField minorField;
    private javax.swing.JLabel minorLabel;
    // End of variables declaration//GEN-END:variables
    
}
