/*
 * MyDeficiency.java
 *
 */

package eye.acolite;

import static eye.acolite.Acolite.forceFileNameExtension;
import static eye.acolite.Acolite.loadImage;
import java.awt.BorderLayout;
import java.awt.CheckboxMenuItem;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;




public class MyDeficiency extends javax.swing.JPanel {
    double angle, tes, sIndex, cIndex;
    private Acolite.Simulation currentSimulation = Acolite.Simulation.normal;
    private Simulator simulator = new Simulator();
    private Image deutanPanel= loadImage("deutanpanel.png");
    private Image protanPanel= loadImage("protanpanel.png");
    private Image tritanPanel= loadImage("tritanpanel.png");
    private boolean currentlySavingImage = false;
    private CheckboxMenuItem normalMenuItem = new CheckboxMenuItem();
    private CheckboxMenuItem deutanMenuItem = new CheckboxMenuItem();
    private CheckboxMenuItem protanMenuItem = new CheckboxMenuItem();
    private CheckboxMenuItem tritanMenuItem = new CheckboxMenuItem();
    private MenuItem saveMenuItem = new MenuItem();
    private MenuItem aboutMenuItem = new MenuItem();
    private MenuItem dichotomousTestMenuItem = new MenuItem();
    private MenuItem myDeficiencyMenuItem = new MenuItem();
    private static final long SLEEP_BEFORE_SCREENSHOT_MILLISECONDS = 300;


    enum Simulation {

        normal, deutan, protan, tritan
    }
    
    public MyDeficiency() {
        initComponents();
        simulateButton.setBorderPainted(false);

        
    }
        private void setIcon() {
       // setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon_48x48.png")));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel1 = new javax.swing.JLabel();
        angleLabel = new javax.swing.JLabel();
        angleField = new javax.swing.JTextField();
        TESLabel = new javax.swing.JLabel();
        TESField = new javax.swing.JTextField();
        SIndexLabel = new javax.swing.JLabel();
        SIndexField = new javax.swing.JTextField();
        CIndexLabel = new javax.swing.JLabel();
        CIndexField = new javax.swing.JTextField();
        simulateButton = new javax.swing.JButton();
        WarningLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        TitleLabel1.setText("D-15 dichotomous test results");

        setBackground(new java.awt.Color(255, 255, 255));

        angleLabel.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        angleLabel.setForeground(new java.awt.Color(240, 79, 63));
        angleLabel.setText("ANGLE");

        angleField.setCaretColor(new java.awt.Color(0, 102, 102));
        angleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angleFieldActionPerformed(evt);
            }
        });

        TESLabel.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        TESLabel.setForeground(new java.awt.Color(240, 79, 63));
        TESLabel.setText("TES");

        TESField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TESFieldActionPerformed(evt);
            }
        });

        SIndexLabel.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        SIndexLabel.setForeground(new java.awt.Color(240, 79, 63));
        SIndexLabel.setText("S-INDEX");

        SIndexField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIndexFieldActionPerformed(evt);
            }
        });

        CIndexLabel.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        CIndexLabel.setForeground(new java.awt.Color(240, 79, 63));
        CIndexLabel.setText("C-INDEX");

        CIndexField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIndexFieldActionPerformed(evt);
            }
        });

        simulateButton.setBackground(new java.awt.Color(255, 255, 255));
        simulateButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        simulateButton.setForeground(new java.awt.Color(144, 31, 98));
        simulateButton.setText("Apply Screen Filter");
        simulateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ika/icons/icon_test.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(simulateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WarningLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SIndexLabel)
                            .addComponent(TESField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SIndexField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TESLabel)
                            .addComponent(angleField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(angleLabel)
                            .addComponent(CIndexField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CIndexLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(angleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(angleField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TESLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TESField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SIndexLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SIndexField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CIndexLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CIndexField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(WarningLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(simulateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void angleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angleFieldActionPerformed
        //String angle = angleField.getText();
    }//GEN-LAST:event_angleFieldActionPerformed

    private void TESFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TESFieldActionPerformed
        //String tes = TESField.getText();
    }//GEN-LAST:event_TESFieldActionPerformed

    private void SIndexFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIndexFieldActionPerformed
        //String sIndex = SIndexField.getText();
    }//GEN-LAST:event_SIndexFieldActionPerformed

    private void CIndexFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIndexFieldActionPerformed
        //String cIndex = CIndexField.getText();
    }//GEN-LAST:event_CIndexFieldActionPerformed

    private void simulateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateButtonActionPerformed
            try {
            angle = Double.parseDouble(angleField.getText());
            tes = Double.parseDouble(TESField.getText());
            sIndex = Double.parseDouble(SIndexField.getText());
            cIndex = Double.parseDouble(CIndexField.getText());
            
            //Confusion Angles
              //normal color vision or slightly colorblind persons have a ratio below 1.2
              if (angle < 66 && angle > 53 && cIndex < 1.2){
                   simulate(Acolite.Simulation.normal);
              }
              //0.7 and up -- protan
              else if (angle > 0.7){
                   simulate(Acolite.Simulation.protan);
              }
              //between -6 and 0.7 -- deutan
              else if(angle < 0.7 && angle > -65){
                   simulate(Acolite.Simulation.deutan);
              }
              //below -65  -- tritan
              else if(angle < -65){
                   simulate(Acolite.Simulation.tritan);
              }
            
            //C-Index  
              if (cIndex < 20 && cIndex > 11){
                  //mild -- strong
              }
              
              if (cIndex < 30 && cIndex > 20){
                  //moderate -- strong
              }
              
              if (cIndex < 40 && cIndex > 30){
                  //moderate -- strong
              }
            } 
            catch (NumberFormatException e) {
                showErrorMessage(e.getMessage(), false);
            }
            
          
          
    }//GEN-LAST:event_simulateButtonActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CIndexField;
    private javax.swing.JLabel CIndexLabel;
    private javax.swing.JTextField SIndexField;
    private javax.swing.JLabel SIndexLabel;
    private javax.swing.JTextField TESField;
    private javax.swing.JLabel TESLabel;
    private javax.swing.JLabel TitleLabel1;
    private javax.swing.JLabel WarningLabel;
    private javax.swing.JTextField angleField;
    private javax.swing.JLabel angleLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton simulateButton;
    // End of variables declaration//GEN-END:variables

     public String cIndexFieldString() {
            return CIndexField.getText();
        }   
    
    private void simulate(Acolite.Simulation simulationType) {
        try {
            // remember the current simulation
            this.currentSimulation = simulationType;

            this.updateMenuState();

            // take a screenshot, simulate and show the result
            this.simulator.simulate(simulationType);
            switch (simulationType) {
                case deutan:
                    this.simulateAndShow(this.deutanPanel);
                    break;
                case protan:
                    this.simulateAndShow(this.protanPanel);
                    break;
                case tritan:
                    this.simulateAndShow(this.tritanPanel);
                    break;
            }
        } catch (Exception exc) {
            exc.printStackTrace();
            this.switchToNormalVision();
        }
    }
    
    private void updateMenuState() {

        // make sure only one menu item is checked
        this.normalMenuItem.setState(this.currentSimulation == Acolite.Simulation.normal);
        this.deutanMenuItem.setState(this.currentSimulation == Acolite.Simulation.deutan);
        this.protanMenuItem.setState(this.currentSimulation == Acolite.Simulation.protan);
        this.tritanMenuItem.setState(this.currentSimulation == Acolite.Simulation.tritan);

        // disable menu items if the Save dialog is in the foreground.
        this.normalMenuItem.setEnabled(!this.currentlySavingImage);
        this.deutanMenuItem.setEnabled(!this.currentlySavingImage);
        this.protanMenuItem.setEnabled(!this.currentlySavingImage);
        this.tritanMenuItem.setEnabled(!this.currentlySavingImage);
        this.aboutMenuItem.setEnabled(!this.currentlySavingImage);

        // Save item is disabled when we are not currently showing a simulation.
        // It is also disabled when the save-as dialog is currently open.
        this.saveMenuItem.setEnabled(this.currentSimulation != Acolite.Simulation.normal && !this.currentlySavingImage);

        // change the title of the save item to the current simulation.
        String saveMenuLabel;
        if (this.currentSimulation != Acolite.Simulation.normal) {
            saveMenuLabel = "Save " + this.currentSimulationName() + " Image...";
        } else {
            saveMenuLabel = "Save Filtered Screen Image...";
        }
        this.saveMenuItem.setLabel(saveMenuLabel);
    }
    

private void simulateAndShow(Image panel) {

        try {
            // wait for a few milliseconds until the menu has faded out.
            Thread.sleep(SLEEP_BEFORE_SCREENSHOT_MILLISECONDS);

            final boolean simulationVisible = Screen.getScreens().size() > 0;

            // detect all attached screens
            if (!simulationVisible) {
                Screen.detectScreens();
            }

            // simulate color-impaired vision for all attached screens
            for (Screen screen : Screen.getScreens()) {

                // don't take a screenshot when a color-impaired simulation 
                // is currently visible. Instead, use the same screenshot again.
                if (!simulationVisible) {
                    screen.takeScreenshot();
                }

                // apply a simulation filter to the screenshot
                BufferedImage img = this.simulator.filter(screen.screenshotImage);
                //img = computeDifference(img, screen.screenshotImage);

                // ImageIO.write(img, "png", new File("screen" + Screen.getScreens().indexOf(screen) + ".png"));

                // show the result of the simulation in a window
                screen.showSimulationImageMyD(img, this, panel);
            }
        } catch (Exception e) {
            e.printStackTrace();
            try {
                this.switchToNormalVision();
            } catch (Exception exc) {
            }
            showErrorMessage(e.getMessage(), false);
            e.printStackTrace();
        }

    }

public void switchToNormalVision() {
        // remember the current simulation
        this.currentSimulation = Acolite.Simulation.normal;

        this.updateMenuState();

        // hide the window
        this.hideSimulation();
    }
private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        this.currentlySavingImage = true;
        try {

            // first get the simulation image
            int screenID = 0; // default is the first screen
            final int screenCount = Screen.getScreens().size();
            if (screenCount > 1) {
                // ask the user for the screen to save when there is more than one
                ArrayList<String> screenNames = new ArrayList<String>(screenCount);
                for (int i = 1; i <= screenCount; i++) {
                    screenNames.add("Screen " + i);
                }
                String screenName = (String) JOptionPane.showInputDialog(null,
                        "Select a Screen:",
                        "Save Filtered Screen Image",
                        JOptionPane.QUESTION_MESSAGE, null,
                        screenNames.toArray(), null);
                if (screenName == null) {
                    return; // user canceled
                }
                screenID = screenNames.indexOf(screenName);
            }
            Image simImg = Screen.getScreens().get(screenID).simulationWindow.getImage();

            // then hide and release the simulation windows
            this.hideSimulation();
            if (simImg == null) {
                throw new Exception("No image to save.");
            }

            // construct file name
            String fileName = this.currentSimulationName() + ".png";

            // disable menu items
            this.updateMenuState();

            // ask user for file to save the image
            String filePath = Acolite.askFile(null, "Save Image", fileName, false);
            if (filePath == null) {
                return;
            }

            // make sure the file has a png extension.
            filePath = forceFileNameExtension(filePath, "png");

            // write the image to a file
            ImageIO.write((BufferedImage) simImg, "png", new File(filePath));
        } catch (Exception e) {
            this.hideSimulation();
            e.printStackTrace();
            String msg = "An unexpected error occurred. \n" + e.getMessage();
            String title = "Acolite Error";
            javax.swing.JOptionPane.showMessageDialog(null, msg, title,
                    javax.swing.JOptionPane.ERROR_MESSAGE, null);
        } finally {
            this.currentlySavingImage = false;

            // re-enable menu items
            this.currentSimulation = Acolite.Simulation.normal;
            this.updateMenuState();
        }
    }

private String currentSimulationName() {
        switch (this.currentSimulation) {
            case deutan:
                return "Deuteranopia";
            case protan:
                return "Protanopia";
            case tritan:
                return "Tritanopia";
            default:
                return "";
        }
    }
private void hideSimulation() {

        for (Screen screen : Screen.getScreens()) {
            screen.hideSimulation();
        }
        Screen.getScreens().clear();

    }

static void showErrorMessage(String msg, boolean showExitButton) {

        if (msg == null || msg.trim().length() < 3) {
            msg = "An error occurred.";
        } else {
            msg = msg.trim();
        }
        String title = "Acolite Error";
        Object[] options = new Object[]{"Exit Acolite"};
        javax.swing.JOptionPane.showOptionDialog(null, msg, title,
                JOptionPane.DEFAULT_OPTION,
                javax.swing.JOptionPane.ERROR_MESSAGE,
                null,
                showExitButton ? options : null,
                showExitButton ? options[0] : null);
    }
}